### ISSUE TITLE
Adding a pool to betacoin.org

### ISSUE THREAD

**Issue by joshdvir** [BetaCoinDev/betacoin#2]
Hi,

Is it possible to add a pool to betacoin.org ?

The pool is at http://bet.l2r.in

Thanks.

**Comment by BetaCoinDev** [comment]
Sure, it will be added to every pool info section, but be ready with your server hardware :)

**Comment by joshdvir** [comment]
:+1:

**Comment by BetaCoinDev** [comment]
seems not working, when it will, post reply here pls.

**Comment by joshdvir** [comment]
Hi, I've had some trouble making it work, i'm using stratum mining and I see that it's working (I see that shares are being accepted) but I'm trying to use MPOS as the front end and I can't seem to get the stats working.
Do you maybe have a working setup that can help me figure it out?
Thanks

**Comment by joshdvir** [comment]
Got it to work, check it out.

Thanks.

**Comment by ghost** [comment]
can you add a new pool please ? http://bet.webcoin.us :) thank you
